on:
  repository_dispatch:
    types: [on-bcr-trigger]
permissions:
  contents: write
jobs:
  deploy:
    uses: ./.github/workflows/deploy.yml
    with:
      bcrCommitHash: ${{ github.event.client_payload.bcrCommitHash }}
    secrets: inherit
